AllCops: 
  NewCops: enable
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 150
Metrics/AbcSize:
  Enabled: False
Metrics/CyclomaticComplexity:
  Enabled: False
Metrics/PerceivedComplexity:
  Enabled: False
Naming/VariableNumber:
  Enabled: False
Style/CombinableLoops:
  Enabled: False